# Copyright (C) 2013-2016 The CyanogenMod Project
# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/msm8226-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/adsprpcd:vendor/bin/adsprpcd \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/btnvtool:vendor/bin/btnvtool \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/dbvc_atvc_property_set:vendor/bin/dbvc_atvc_property_set \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/hci_qcomm_init:vendor/bin/hci_qcomm_init \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/irsc_util:vendor/bin/irsc_util \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/location-mq:vendor/bin/location-mq \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/mm-qcamera-daemon:vendor/bin/mm-qcamera-daemon \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/mpdecision:vendor/bin/mpdecision \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/netmgrd:vendor/bin/netmgrd \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/qmi_motext_hook:vendor/bin/qmi_motext_hook \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/qmuxd:vendor/bin/qmuxd \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/qseecomd:vendor/bin/qseecomd \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/radish:vendor/bin/radish \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/rfs_access:vendor/bin/rfs_access \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/rmt_storage:vendor/bin/rmt_storage \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/thermal-engine:vendor/bin/thermal-engine \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/time_daemon:vendor/bin/time_daemon \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/a300_pfp.fw:vendor/firmware/a300_pfp.fw \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/a300_pm4.fw:vendor/firmware/a300_pm4.fw \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/a330_pfp.fw:vendor/firmware/a330_pfp.fw \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/a330_pm4.fw:vendor/firmware/a330_pm4.fw \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:vendor/firmware/cpp_firmware_v1_1_1.fw \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:vendor/firmware/cpp_firmware_v1_1_6.fw \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:vendor/firmware/cpp_firmware_v1_2_0.fw \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/venus.b00:vendor/firmware/venus.b00 \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/venus.b01:vendor/firmware/venus.b01 \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/venus.b02:vendor/firmware/venus.b02 \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/venus.b03:vendor/firmware/venus.b03 \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/venus.b04:vendor/firmware/venus.b04 \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/venus.mbn:vendor/firmware/venus.mbn \
    vendor/motorola/msm8226-common/proprietary/vendor/firmware/venus.mdt:vendor/firmware/venus.mdt \
    vendor/motorola/msm8226-common/proprietary/vendor/etc/gps.conf:vendor/etc/gps.conf \
    vendor/motorola/msm8226-common/proprietary/vendor/etc/izat.conf:vendor/etc/izat.conf \
    vendor/motorola/msm8226-common/proprietary/vendor/etc/permissions/qcnvitems.xml:vendor/etc/permissions/qcnvitems.xml \
    vendor/motorola/msm8226-common/proprietary/vendor/etc/permissions/qcrilhook.xml:vendor/etc/permissions/qcrilhook.xml \
    vendor/motorola/msm8226-common/proprietary/vendor/etc/quipc.conf:vendor/etc/quipc.conf \
    vendor/motorola/msm8226-common/proprietary/vendor/etc/sap.conf:vendor/etc/sap.conf \
    vendor/motorola/msm8226-common/proprietary/vendor/etc/xtra_root_cert.pem:vendor/etc/xtra_root_cert.pem \
    vendor/motorola/msm8226-common/proprietary/vendor/etc/xtwifi.conf:vendor/etc/xtwifi.conf \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libadropbox.so:vendor/lib/libadropbox.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ar0543_common.so:vendor/lib/libchromatix_ar0543_common.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ar0543_default_video.so:vendor/lib/libchromatix_ar0543_default_video.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ar0543_hfr_60.so:vendor/lib/libchromatix_ar0543_hfr_60.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ar0543_preview.so:vendor/lib/libchromatix_ar0543_preview.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ar0543_snapshot.so:vendor/lib/libchromatix_ar0543_snapshot.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libloc_api_v02.so:vendor/lib/libloc_api_v02.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libloc_ds_api.so:vendor/lib/libloc_ds_api.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmdmcutback.so:vendor/lib/libmdmcutback.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmdmdetect.so:vendor/lib/libmdmdetect.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_ar0543.so:vendor/lib/libmmcamera_ar0543.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmjpeg_interface.so:vendor/lib/libmmjpeg_interface.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmot_sensorlistener.so:vendor/lib/libmot_sensorlistener.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libOmxVdecHevc.so:vendor/lib/libOmxVdecHevc.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqmimotext.so:vendor/lib/libqmimotext.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqomx_core.so:vendor/lib/libqomx_core.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/egl/eglsubAndroid.so:vendor/lib/egl/eglsubAndroid.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/egl/libEGL_adreno.so:vendor/lib/egl/libEGL_adreno.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/egl/libGLESv2_adreno.so:vendor/lib/egl/libGLESv2_adreno.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/egl/libq3dtools_adreno.so:vendor/lib/egl/libq3dtools_adreno.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libC2D2.so:vendor/lib/libC2D2.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libCB.so:vendor/lib/libCB.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libDivxDrm.so:vendor/lib/libDivxDrm.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libI420colorconvert.so:vendor/lib/libI420colorconvert.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libOmxAacDec.so:vendor/lib/libOmxAacDec.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libOmxAmrwbplusDec.so:vendor/lib/libOmxAmrwbplusDec.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libOmxEvrcDec.so:vendor/lib/libOmxEvrcDec.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libOmxQcelp13Dec.so:vendor/lib/libOmxQcelp13Dec.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libOmxWmaDec.so:vendor/lib/libOmxWmaDec.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libOpenCL.so:vendor/lib/libOpenCL.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libQSEEComAPI.so:vendor/lib/libQSEEComAPI.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libRSDriver_adreno.so:vendor/lib/libRSDriver_adreno.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libSHIMDivxDrm.so:vendor/lib/libSHIMDivxDrm.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libTimeService.so:vendor/lib/libTimeService.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libacdbloader.so:vendor/lib/libacdbloader.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libacdbmapper.so:vendor/lib/libacdbmapper.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libacdbrtac.so:vendor/lib/libacdbrtac.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libadiertac.so:vendor/lib/libadiertac.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libadreno_utils.so:vendor/lib/libadreno_utils.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libadsprpc.so:vendor/lib/libadsprpc.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libaudcal.so:vendor/lib/libaudcal.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libaudioalsa.so:vendor/lib/libaudioalsa.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libbccQTI.so:vendor/lib/libbccQTI.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libbt-vendor.so:vendor/lib/libbt-vendor.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libbtnv.so:vendor/lib/libbtnv.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libc2d30-a3xx.so:vendor/lib/libc2d30-a3xx.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_imx132_common.so:vendor/lib/libchromatix_imx132_common.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_imx132_preview.so:vendor/lib/libchromatix_imx132_preview.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_imx132_snapshot.so:vendor/lib/libchromatix_imx132_snapshot.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_imx132_video.so:vendor/lib/libchromatix_imx132_video.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_imx179_common.so:vendor/lib/libchromatix_imx179_common.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_imx179_default_video.so:vendor/lib/libchromatix_imx179_default_video.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_imx179_hfr_60.so:vendor/lib/libchromatix_imx179_hfr_60.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_imx179_preview.so:vendor/lib/libchromatix_imx179_preview.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_imx179_snapshot.so:vendor/lib/libchromatix_imx179_snapshot.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ov8865_common.so:vendor/lib/libchromatix_ov8865_common.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ov8865_default_video.so:vendor/lib/libchromatix_ov8865_default_video.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ov8865_hfr_120fps.so:vendor/lib/libchromatix_ov8865_hfr_120fps.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ov8865_hfr_60fps.so:vendor/lib/libchromatix_ov8865_hfr_60fps.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ov8865_hfr_90fps.so:vendor/lib/libchromatix_ov8865_hfr_90fps.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ov8865_liveshot.so:vendor/lib/libchromatix_ov8865_liveshot.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ov8865_preview.so:vendor/lib/libchromatix_ov8865_preview.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ov8865_snapshot.so:vendor/lib/libchromatix_ov8865_snapshot.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ov8865_video_hd.so:vendor/lib/libchromatix_ov8865_video_hd.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_ov8865_zsl.so:vendor/lib/libchromatix_ov8865_zsl.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_t4k71_common.so:vendor/lib/libchromatix_t4k71_common.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_t4k71_fhd_30fps.so:vendor/lib/libchromatix_t4k71_fhd_30fps.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_t4k71_fhd_30fps_video.so:vendor/lib/libchromatix_t4k71_fhd_30fps_video.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_t4k71_fhd_60fps.so:vendor/lib/libchromatix_t4k71_fhd_60fps.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_t4k71_hd_30fps.so:vendor/lib/libchromatix_t4k71_hd_30fps.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libchromatix_t4k71_hd_60fps.so:vendor/lib/libchromatix_t4k71_hd_60fps.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libcneapiclient.so:vendor/lib/libcneapiclient.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libconfigdb.so:vendor/lib/libconfigdb.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libdiag.so:vendor/lib/libdiag.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libdrmfs.so:vendor/lib/libdrmfs.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libdrmtime.so:vendor/lib/libdrmtime.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libdsi_netctrl.so:vendor/lib/libdsi_netctrl.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libdsutils.so:vendor/lib/libdsutils.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libfastcvadsp_stub.so:vendor/lib/libfastcvadsp_stub.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libfastcvopt.so:vendor/lib/libfastcvopt.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libgeofence.so:vendor/lib/libgeofence.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libgsl.so:vendor/lib/libgsl.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libHevcSwDecoder.so:vendor/lib/libHevcSwDecoder.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libidl.so:vendor/lib/libidl.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libizat_core.so:vendor/lib/libizat_core.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libjpegdhw.so:vendor/lib/libjpegdhw.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libjpegehw.so:vendor/lib/libjpegehw.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/liblbs_core.so:vendor/lib/liblbs_core.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libllvm-qcom.so:vendor/lib/libllvm-qcom.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmm-color-convertor.so:vendor/lib/libmm-color-convertor.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_faceproc.so:vendor/lib/libmmcamera_faceproc.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_hdr_lib.so:vendor/lib/libmmcamera_hdr_lib.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_imglib.so:vendor/lib/libmmcamera_imglib.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_imx132.so:vendor/lib/libmmcamera_imx132.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_imx132_eeprom.so:vendor/lib/libmmcamera_imx132_eeprom.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_imx179.so:vendor/lib/libmmcamera_imx179.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_mt9m114.so:vendor/lib/libmmcamera_mt9m114.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_ov8865.so:vendor/lib/libmmcamera_ov8865.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_t4k71.so:vendor/lib/libmmcamera_t4k71.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_tintless_algo.so:vendor/lib/libmmcamera_tintless_algo.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_tuning.so:vendor/lib/libmmcamera_tuning.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmipl.so:vendor/lib/libmmipl.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmjpeg.so:vendor/lib/libmmjpeg.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmosal.so:vendor/lib/libmmosal.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmmqjpeg_codec.so:vendor/lib/libmmqjpeg_codec.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libmotext_inf.so:vendor/lib/libmotext_inf.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libnetmgr.so:vendor/lib/libnetmgr.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqc-opt.so:vendor/lib/libqc-opt.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqcci_legacy.so:vendor/lib/libqcci_legacy.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqdi.so:vendor/lib/libqdi.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqdp.so:vendor/lib/libqdp.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqmi.so:vendor/lib/libqmi.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqmi_cci.so:vendor/lib/libqmi_cci.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqmi_client_qmux.so:vendor/lib/libqmi_client_qmux.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqmi_common_so.so:vendor/lib/libqmi_common_so.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqmi_csi.so:vendor/lib/libqmi_csi.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqmi_csvt_srvc.so:vendor/lib/libqmi_csvt_srvc.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqmi_encdec.so:vendor/lib/libqmi_encdec.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqmiservices.so:vendor/lib/libqmiservices.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqomx_jpegdec.so:vendor/lib/libqomx_jpegdec.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqomx_jpegenc.so:vendor/lib/libqomx_jpegenc.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libqti-perfd-client.so:vendor/lib/libqti-perfd-client.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libril-qc-qmi-1.so:vendor/lib/libril-qc-qmi-1.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libril-qcril-hook-oem.so:vendor/lib/libril-qcril-hook-oem.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/librpmb.so:vendor/lib/librpmb.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/librs_adreno.so:vendor/lib/librs_adreno.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/librs_adreno_sha1.so:vendor/lib/librs_adreno_sha1.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libsc-a3xx.so:vendor/lib/libsc-a3xx.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libscale.so:vendor/lib/libscale.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libscve.so:vendor/lib/libscve.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libsmemlog.so:vendor/lib/libsmemlog.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libssd.so:vendor/lib/libssd.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libsystem_health_mon.so:vendor/lib/libsystem_health_mon.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libthermalclient.so:vendor/lib/libthermalclient.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libthermalioctl.so:vendor/lib/libthermalioctl.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libtime_genoff.so:vendor/lib/libtime_genoff.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libxml.so:vendor/lib/libxml.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/libwvhidl.so:vendor/lib/libwvhidl.so \
    vendor/motorola/msm8226-common/proprietary/vendor/bin/hw/android.hardware.drm@1.0-service.widevine:vendor/bin/hw/android.hardware.drm@1.0-service.widevine \
    vendor/motorola/msm8226-common/proprietary/vendor/etc/init/android.hardware.drm@1.0-service.widevine.rc:vendor/etc/init/android.hardware.drm@1.0-service.widevine.rc \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so:vendor/lib/rfsa/adsp/libadsp_denoise_skel.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/rfsa/adsp/libdspCV_skel.so:vendor/lib/rfsa/adsp/libdspCV_skel.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp.so:vendor/lib/rfsa/adsp/libfastcvadsp.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/rfsa/adsp/libfastcvadsp_skel.so:vendor/lib/rfsa/adsp/libfastcvadsp_skel.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/soundfx/libqcbassboost.so:vendor/lib/soundfx/libqcbassboost.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/soundfx/libqcreverb.so:vendor/lib/soundfx/libqcreverb.so \
    vendor/motorola/msm8226-common/proprietary/vendor/lib/soundfx/libqcvirt.so:vendor/lib/soundfx/libqcvirt.so

PRODUCT_PACKAGES += \
    TimeService \
    qcrilmsgtunnel \
    qcnvitems \
    qcrilhook
